name: catshop
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  page_transition: "^2.0.5"
  rflutter_alert: ^2.0.2
  shared_preferences: ^2.0.20
  splashscreen: ^1.3.5
  get: ^4.6.3
  provider: ^6.0.5
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  google_sign_in: ^6.1.3
  intl: ^0.17.0
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/adrian.jpeg
    - assets/images/asril.jpg
    - assets/images/riana.jpg
    - assets/images/silvia.jpg
    - assets/images/petshop_logo.png

  fonts:
      - family: RubikMoonrocks
        fonts:
          - asset: assets/fonts/RubikMoonrocks-Regular.ttf
      - family: RussoOne
        fonts:
          - asset: assets/fonts/RussoOne-Regular.ttf
      - family: Acme
        fonts:
          - asset: assets/fonts/Acme-Regular.ttf
      - family: Fjalla
        fonts:
          - asset: assets/fonts/FjallaOne-Regular.ttf